// Copyright (c) 2026 Kevin Herro
// SPDX-License-Identifier: MIT

package maintain

import (
	"archive/tar"
	"compress/gzip"
	"context"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/kevherro/dpm/internal/checksum"
	"github.com/kevherro/dpm/internal/config"
	"github.com/kevherro/dpm/internal/install"
	"github.com/kevherro/dpm/internal/manifest"
	"github.com/kevherro/dpm/internal/registry"
)

const (
	targetOS   = "darwin"
	targetArch = "arm64"
)

// PrepareOptions configures a package manifest preparation run.
type PrepareOptions struct {
	RegistryRoot      string
	Name              string
	Version           string
	ArtifactURL       string
	Summary           string
	Homepage          string
	License           string
	Categories        []string
	Dependencies      []string
	Bins              []string
	SkipInstallVerify bool
	Client            *http.Client
}

// PrepareResult reports files and metadata generated by Prepare.
type PrepareResult struct {
	Name            string
	Version         string
	ArtifactURL     string
	Size            int64
	ContentType     string
	SHA256          string
	SuggestedBins   []string
	Bins            []string
	CreatedFiles    []string
	VerifiedInstall bool
	Diff            string
}

type assetMetadata struct {
	Path        string
	Size        int64
	ContentType string
}

// Prepare creates package metadata and a version manifest from one artifact.
func Prepare(ctx context.Context, opts PrepareOptions) (PrepareResult, error) {
	if opts.RegistryRoot == "" {
		return PrepareResult{}, fmt.Errorf("registry path is required")
	}
	if opts.Name == "" {
		return PrepareResult{}, fmt.Errorf("package name is required")
	}
	if opts.Version == "" {
		return PrepareResult{}, fmt.Errorf("package version is required")
	}
	if opts.ArtifactURL == "" {
		return PrepareResult{}, fmt.Errorf("artifact url is required")
	}

	reg, err := registry.New(opts.RegistryRoot)
	if err != nil {
		return PrepareResult{}, err
	}
	if _, err := reg.PackageDir(opts.Name); err != nil {
		return PrepareResult{}, err
	}
	manifestPath, err := reg.ManifestPath(opts.Name, opts.Version)
	if err != nil {
		return PrepareResult{}, err
	}
	if _, err := os.Stat(manifestPath); err == nil {
		return PrepareResult{}, fmt.Errorf("%s already exists", manifestPath)
	} else if !os.IsNotExist(err) {
		return PrepareResult{}, fmt.Errorf("stat manifest %s: %w", manifestPath, err)
	}

	workDir, err := os.MkdirTemp("", "dpm-maintain-*")
	if err != nil {
		return PrepareResult{}, fmt.Errorf("create maintainer work directory: %w", err)
	}
	defer os.RemoveAll(workDir)

	client := opts.Client
	if client == nil {
		client = &http.Client{Timeout: 30 * time.Second}
	}
	artifactPath := filepath.Join(workDir, "artifact.tar.gz")
	asset, err := fetchAsset(ctx, client, opts.ArtifactURL, artifactPath)
	if err != nil {
		return PrepareResult{}, err
	}
	sum, err := checksum.FileSHA256(asset.Path)
	if err != nil {
		return PrepareResult{}, err
	}
	suggestedBins, err := inspectTarGz(asset.Path)
	if err != nil {
		return PrepareResult{}, err
	}
	bins := slices.Clone(opts.Bins)
	if len(bins) == 0 {
		bins = slices.Clone(suggestedBins)
	}
	if len(bins) == 0 {
		return PrepareResult{}, fmt.Errorf("archive has no executable files; pass --bin to declare install bins")
	}
	manifestContents, err := manifestFile(opts, sum, bins)
	if err != nil {
		return PrepareResult{}, err
	}

	created := map[string][]byte{}
	createdFiles := []string{}
	pkgPath, pkgContents, err := packageMetadataFile(reg, opts)
	if err != nil {
		return PrepareResult{}, err
	}
	if pkgContents != nil {
		if err := writeNewFile(pkgPath, pkgContents); err != nil {
			return PrepareResult{}, err
		}
		created[pkgPath] = pkgContents
		createdFiles = append(createdFiles, pkgPath)
	}

	if err := writeNewFile(manifestPath, manifestContents); err != nil {
		return PrepareResult{}, err
	}
	created[manifestPath] = manifestContents
	createdFiles = append(createdFiles, manifestPath)

	if err := validatePreparedRegistry(ctx, reg.Root); err != nil {
		return PrepareResult{}, err
	}
	verified := false
	if !opts.SkipInstallVerify {
		if err := verifyPreparedInstall(ctx, client, reg.Root, opts.Name); err != nil {
			return PrepareResult{}, err
		}
		verified = true
	}
	diff, err := renderReviewDiff(reg.Root, created)
	if err != nil {
		return PrepareResult{}, err
	}

	return PrepareResult{
		Name:            opts.Name,
		Version:         opts.Version,
		ArtifactURL:     opts.ArtifactURL,
		Size:            asset.Size,
		ContentType:     asset.ContentType,
		SHA256:          sum,
		SuggestedBins:   suggestedBins,
		Bins:            bins,
		CreatedFiles:    createdFiles,
		VerifiedInstall: verified,
		Diff:            diff,
	}, nil
}

func fetchAsset(ctx context.Context, client *http.Client, rawURL, dst string) (assetMetadata, error) {
	if err := validateArtifactURL(rawURL); err != nil {
		return assetMetadata{}, err
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return assetMetadata{}, fmt.Errorf("parse artifact url %q: %w", rawURL, err)
	}

	switch u.Scheme {
	case "file":
		path, err := fileURLPath(rawURL)
		if err != nil {
			return assetMetadata{}, err
		}
		size, err := copyAssetFile(dst, path)
		if err != nil {
			return assetMetadata{}, err
		}
		return assetMetadata{Path: dst, Size: size}, nil
	case "https":
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
		if err != nil {
			return assetMetadata{}, fmt.Errorf("create artifact request %q: %w", rawURL, err)
		}
		resp, err := client.Do(req)
		if err != nil {
			return assetMetadata{}, fmt.Errorf("fetch artifact %q: %w", rawURL, err)
		}
		defer resp.Body.Close()
		if resp.StatusCode < 200 || resp.StatusCode > 299 {
			return assetMetadata{}, fmt.Errorf("fetch artifact %q: unexpected status %s", rawURL, resp.Status)
		}
		size, err := writeAsset(dst, resp.Body)
		if err != nil {
			return assetMetadata{}, fmt.Errorf("write artifact %q: %w", rawURL, err)
		}
		return assetMetadata{Path: dst, Size: size, ContentType: resp.Header.Get("Content-Type")}, nil
	default:
		return assetMetadata{}, fmt.Errorf("unsupported artifact url scheme %q", u.Scheme)
	}
}

func validateArtifactURL(rawURL string) error {
	if rawURL == "" {
		return fmt.Errorf("artifact url is required")
	}
	u, err := url.Parse(rawURL)
	if err != nil {
		return fmt.Errorf("parse artifact url %q: %w", rawURL, err)
	}
	if u.Scheme != "file" && u.Scheme != "https" {
		return fmt.Errorf("unsupported artifact url scheme %q", u.Scheme)
	}
	lower := strings.ToLower(rawURL)
	if strings.Contains(lower, "latest") {
		return fmt.Errorf("artifact url %q looks mutable: latest downloads are not allowed", rawURL)
	}
	if strings.Contains(lower, "/archive/main.") ||
		strings.Contains(lower, "/archive/master.") ||
		strings.Contains(lower, "/archive/refs/heads/") {
		return fmt.Errorf("artifact url %q looks mutable: branch archives are not allowed", rawURL)
	}

	return nil
}

func fileURLPath(rawURL string) (string, error) {
	path, ok := strings.CutPrefix(rawURL, "file://")
	if !ok {
		return "", fmt.Errorf("artifact url %q is not a file url", rawURL)
	}
	if path == "" {
		return "", fmt.Errorf("file artifact url %q has empty path", rawURL)
	}
	path, err := url.PathUnescape(path)
	if err != nil {
		return "", fmt.Errorf("decode file artifact url %q: %w", rawURL, err)
	}

	return path, nil
}

func copyAssetFile(dst, src string) (int64, error) {
	f, err := os.Open(src)
	if err != nil {
		return 0, fmt.Errorf("open file artifact %s: %w", src, err)
	}
	defer f.Close()

	size, err := writeAsset(dst, f)
	if err != nil {
		return 0, fmt.Errorf("copy file artifact %s: %w", src, err)
	}

	return size, nil
}

func writeAsset(dst string, r io.Reader) (int64, error) {
	f, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return 0, fmt.Errorf("create artifact %s: %w", dst, err)
	}
	defer f.Close()

	n, err := io.Copy(f, r)
	if err != nil {
		return 0, err
	}

	return n, nil
}

func inspectTarGz(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open archive %s: %w", path, err)
	}
	defer f.Close()

	gz, err := gzip.NewReader(f)
	if err != nil {
		return nil, fmt.Errorf("open gzip archive %s: %w", path, err)
	}
	defer gz.Close()

	var bins []string
	tr := tar.NewReader(gz)
	for {
		header, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("read tar header from %s: %w", path, err)
		}
		name, err := safeArchiveName(header.Name)
		if err != nil {
			return nil, err
		}
		switch header.Typeflag {
		case tar.TypeDir:
			continue
		case tar.TypeReg, tar.TypeRegA:
			if header.FileInfo().Mode().Perm()&0o111 != 0 {
				bins = append(bins, name)
			}
		case tar.TypeSymlink, tar.TypeLink:
			return nil, fmt.Errorf("archive entry %q uses links, which are not allowed", header.Name)
		default:
			return nil, fmt.Errorf("archive entry %q has unsupported type %q", header.Name, header.Typeflag)
		}
	}
	slices.Sort(bins)

	return bins, nil
}

func safeArchiveName(name string) (string, error) {
	if name == "" {
		return "", fmt.Errorf("archive entry has empty path")
	}
	if strings.Contains(name, `\`) {
		return "", fmt.Errorf("archive entry %q contains backslash path separators", name)
	}
	clean := filepath.Clean(name)
	if !filepath.IsLocal(clean) {
		return "", fmt.Errorf("archive entry %q escapes extraction root", name)
	}

	return clean, nil
}

func packageMetadataFile(reg registry.Registry, opts PrepareOptions) (string, []byte, error) {
	pkgDir, err := reg.PackageDir(opts.Name)
	if err != nil {
		return "", nil, err
	}
	path := filepath.Join(pkgDir, registry.PackageFile)
	if _, err := os.Stat(path); err == nil {
		if _, err := reg.Package(opts.Name); err != nil {
			return "", nil, err
		}
		return path, nil, nil
	} else if !os.IsNotExist(err) {
		return "", nil, fmt.Errorf("stat package metadata %s: %w", path, err)
	}
	if opts.Summary == "" {
		return "", nil, fmt.Errorf("summary is required when creating package metadata")
	}
	if opts.Homepage == "" {
		return "", nil, fmt.Errorf("homepage is required when creating package metadata")
	}
	if opts.License == "" {
		return "", nil, fmt.Errorf("license is required when creating package metadata")
	}
	pkg := registry.Package{
		Schema:     registry.CurrentSchema,
		Name:       opts.Name,
		Summary:    opts.Summary,
		Homepage:   opts.Homepage,
		License:    opts.License,
		Categories: slices.Clone(opts.Categories),
	}
	if err := registry.ValidatePackage(pkg); err != nil {
		return "", nil, err
	}

	return path, packageMetadataContents(pkg), nil
}

func packageMetadataContents(pkg registry.Package) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "schema = %d\n", registry.CurrentSchema)
	fmt.Fprintf(&b, "name = %s\n", strconv.Quote(pkg.Name))
	fmt.Fprintf(&b, "summary = %s\n", strconv.Quote(pkg.Summary))
	fmt.Fprintf(&b, "homepage = %s\n", strconv.Quote(pkg.Homepage))
	fmt.Fprintf(&b, "license = %s\n", strconv.Quote(pkg.License))
	fmt.Fprintf(&b, "categories = %s\n", quoteArray(pkg.Categories))

	return []byte(b.String())
}

func manifestFile(opts PrepareOptions, sum string, bins []string) ([]byte, error) {
	m := manifest.Manifest{
		Schema:       manifest.CurrentSchema,
		Name:         opts.Name,
		Version:      opts.Version,
		Dependencies: slices.Clone(opts.Dependencies),
		Yanked:       false,
		Artifacts: []manifest.Artifact{
			{
				OS:     targetOS,
				Arch:   targetArch,
				URL:    opts.ArtifactURL,
				SHA256: sum,
			},
		},
		Install: manifest.Install{Bins: slices.Clone(bins)},
	}
	if err := manifest.Validate(m); err != nil {
		return nil, err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "schema = %d\n", manifest.CurrentSchema)
	fmt.Fprintf(&b, "name = %s\n", strconv.Quote(m.Name))
	fmt.Fprintf(&b, "version = %s\n", strconv.Quote(m.Version))
	fmt.Fprintf(&b, "dependencies = %s\n", quoteArray(m.Dependencies))
	fmt.Fprintf(&b, "yanked = false\n\n")
	fmt.Fprintf(&b, "[[artifacts]]\n")
	fmt.Fprintf(&b, "os = %s\n", strconv.Quote(targetOS))
	fmt.Fprintf(&b, "arch = %s\n", strconv.Quote(targetArch))
	fmt.Fprintf(&b, "url = %s\n", strconv.Quote(opts.ArtifactURL))
	fmt.Fprintf(&b, "sha256 = %s\n\n", strconv.Quote(sum))
	fmt.Fprintf(&b, "[install]\n")
	fmt.Fprintf(&b, "bins = %s\n", quoteArray(m.Install.Bins))

	return []byte(b.String()), nil
}

func quoteArray(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, strconv.Quote(value))
	}

	return "[" + strings.Join(quoted, ", ") + "]"
}

func writeNewFile(path string, contents []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create parent directory %s: %w", filepath.Dir(path), err)
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		if os.IsExist(err) {
			return fmt.Errorf("%s already exists", path)
		}
		return fmt.Errorf("create %s: %w", path, err)
	}
	defer f.Close()
	if _, err := f.Write(contents); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}

	return nil
}

func validatePreparedRegistry(ctx context.Context, root string) error {
	report, err := registry.Validate(ctx, registry.ValidateOptions{Root: root})
	if err != nil {
		return err
	}
	if report.Valid() {
		return nil
	}
	var b strings.Builder
	fmt.Fprintf(&b, "prepared registry is invalid")
	for _, issue := range report.Issues {
		fmt.Fprintf(&b, "\n%s: %s", issue.Path, issue.Message)
	}

	return fmt.Errorf("%s", b.String())
}

func verifyPreparedInstall(ctx context.Context, client *http.Client, registryRoot, name string) error {
	root, err := os.MkdirTemp("", "dpm-verify-*")
	if err != nil {
		return fmt.Errorf("create install verification root: %w", err)
	}
	defer os.RemoveAll(root)

	cfg, err := config.FromRoot(root)
	if err != nil {
		return err
	}
	if err := copyRegistry(registryRoot, cfg.RegistryDir); err != nil {
		return err
	}
	installer := install.Installer{
		Fetcher: install.ArtifactFetcher{Client: client},
		GOOS:    targetOS,
		GOARCH:  targetArch,
	}
	if _, err := installer.Install(ctx, cfg, name); err != nil {
		return fmt.Errorf("verify local install for %s: %w", name, err)
	}

	return nil
}

func copyRegistry(src, dst string) error {
	return filepath.WalkDir(src, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return fmt.Errorf("compare registry path %s to %s: %w", path, src, err)
		}
		if rel == "." {
			return os.MkdirAll(dst, 0o755)
		}
		if rel == ".git" || strings.HasPrefix(rel, ".git"+string(filepath.Separator)) {
			if entry.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}
		target := filepath.Join(dst, rel)
		if entry.Type()&os.ModeSymlink != 0 {
			return fmt.Errorf("registry symlink %s is not supported during install verification", path)
		}
		if entry.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		info, err := entry.Info()
		if err != nil {
			return fmt.Errorf("stat registry file %s: %w", path, err)
		}
		return copyRegularFile(path, target, info.Mode().Perm())
	})
}

func copyRegularFile(src, dst string, perm os.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return fmt.Errorf("open registry file %s: %w", src, err)
	}
	defer in.Close()
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return fmt.Errorf("create registry file parent %s: %w", filepath.Dir(dst), err)
	}
	out, err := os.OpenFile(dst, os.O_WRONLY|os.O_CREATE|os.O_EXCL, perm)
	if err != nil {
		return fmt.Errorf("create registry file %s: %w", dst, err)
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return fmt.Errorf("copy registry file %s: %w", src, err)
	}

	return nil
}

func renderReviewDiff(root string, files map[string][]byte) (string, error) {
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	slices.Sort(paths)

	var b strings.Builder
	for _, path := range paths {
		diff, err := renderNewFileDiff(root, path, files[path])
		if err != nil {
			return "", err
		}
		b.WriteString(diff)
	}

	return b.String(), nil
}

func renderNewFileDiff(root, path string, contents []byte) (string, error) {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return "", fmt.Errorf("compare generated file %s to registry root %s: %w", path, root, err)
	}
	rel = filepath.ToSlash(rel)
	text := string(contents)
	lineCount := strings.Count(text, "\n")
	if text != "" && !strings.HasSuffix(text, "\n") {
		lineCount++
	}

	var b strings.Builder
	fmt.Fprintf(&b, "diff --git a/%s b/%s\n", rel, rel)
	fmt.Fprintf(&b, "new file mode 100644\n")
	fmt.Fprintf(&b, "--- /dev/null\n")
	fmt.Fprintf(&b, "+++ b/%s\n", rel)
	fmt.Fprintf(&b, "@@ -0,0 +1,%d @@\n", lineCount)
	for _, line := range strings.SplitAfter(text, "\n") {
		if line == "" {
			continue
		}
		b.WriteByte('+')
		b.WriteString(line)
		if !strings.HasSuffix(line, "\n") {
			b.WriteByte('\n')
		}
	}

	return b.String(), nil
}
